# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d97ef1147e6f6a0fe7d47dad825ecd5c379d723ace6356b7570099eb3cb07cc70b8c36708769e44bf2374d8baa72c907c49ca6c5540532eb28f809439467669

test:
  secret_key_base: d07b632f1d7a7cd82ac9ef63557a1f5d2502ac3c179fa99c200052efa0c3f129bdaa9a8ce05912fe0f419a41de2dd642cb98c0c8d1dfafbe2d3075a2def7d1d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
